export const CITY_PORTALS: Record<string, any> = {
  "01": {
    name: "Adana",
    archetype: "Fire",
    core: "Raw power. Pent-up energy. Call to action.",
  },
  "02": {
    name: "Adıyaman",
    archetype: "Depth",
    core: "Silent consciousness. Inner cave.",
  },
  "03": {
    name: "Opium",
    archetype: "Purification",
    core: "Slow down. Clear. Start over.",
  },
  "04": { name: "Pain", archetype: "Summit", core: "Lonely rise. Will test." },
  "05": {
    name: "Amasya",
    archetype: "Date",
    core: "History code. Ancestral memory.",
  },
  "06": {
    name: "Ankara",
    archetype: "Center",
    core: "Cold mind. Decision area.",
  },
  "07": { name: "Antalya", archetype: "Işık", core: "Joy. Life energy." },
  "08": { name: "Artvin", archetype: "Nature", core: "Wild intuition." },
  "09": {
    name: "Enlightened",
    archetype: "Enlightenment",
    core: "Light of awareness.",
  },
  "10": {
    name: "Balıkesir",
    archetype: "Transition",
    core: "Between two frequencies.",
  },
  "11": { name: "Bilecik", archetype: "Seed", core: "Small start." },
  "12": { name: "Bingöl", archetype: "Layer", core: "Multiple consciousness." },
  "13": { name: "Bitlis", archetype: "Shadow", core: "Suppressed side." },
  "14": {
    name: "Bolu",
    archetype: "Sis",
    core: "The truth that does not become clear.",
  },
  "15": { name: "Burdur", archetype: "Reflection", core: "Inner mirror." },
  "16": { name: "Bursa", archetype: "Kök", core: "Köklü güç." },
  "17": {
    name: "Çanakkale",
    archetype: "Threshold",
    core: "Sacrifice frequency.",
  },
  "18": { name: "Çankırı", archetype: "Patience", core: "Slow progress." },
  "19": { name: "Çorum", archetype: "Trace", core: "Old symbol." },
  "20": { name: "Denizli", archetype: "Flow", core: "Drop and move forward." },
  "21": { name: "Diyarbakır", archetype: "Taş", core: "Sert irade." },
  "22": { name: "Edirne", archetype: "Kapı", core: "Border awareness." },
  "23": {
    name: "Elazığ",
    archetype: "Vibration",
    core: "Frequency transition.",
  },
  "24": {
    name: "Erzincan",
    archetype: "Fracture",
    core: "Fault line consciousness.",
  },
  "25": { name: "Erzurum", archetype: "Cold", core: "Frozen emotion." },
  "26": { name: "Eskişehir", archetype: "Youth", core: "Fresh consciousness." },
  "27": { name: "Gaziantep", archetype: "Production", core: "Creation fire." },
  "28": {
    name: "Giresun",
    archetype: "Dalga",
    core: "Emotional ups and downs.",
  },
  "29": { name: "Gümüşhane", archetype: "Mine", core: "Treasure in the deep." },
  "30": { name: "Hakkari", archetype: "Border", core: "Three consciousness." },
  "31": { name: "Hatay", archetype: "Unity", core: "Harmony in multiplicity." },
  "32": { name: "Isparta", archetype: "Smell", core: "Memory trigger." },
  "33": { name: "Mersin", archetype: "Expansion", core: "Coastal frequency." },
  "34": { name: "Istanbul", archetype: "Portal", core: "East-West gateway." },
  "35": { name: "Izmir", archetype: "Freedom", core: "Lightness of heart." },
  "36": { name: "Kars", archetype: "Cold memory", core: "Old traces." },
  "37": { name: "Kastamonu", archetype: "Forest", core: "Inner exploration." },
  "38": { name: "Kayseri", archetype: "Strategy", core: "Smart move." },
  "39": { name: "Kırklareli", archetype: "Threshold area", core: "Gateway." },
  "40": { name: "Kırşehir", archetype: "Ritüel", core: "Sessiz ibadet." },
  "41": {
    name: "Kocaeli",
    archetype: "Machine",
    core: "The system is running.",
  },
  "42": { name: "Konya", archetype: "Return", core: "Whirling dervishes." },
  "43": { name: "Kütahya", archetype: "Seramik", core: "Kırılgan yapı." },
  "44": { name: "Malatya", archetype: "Tat", core: "Bittersweet experience." },
  "45": { name: "Manisa", archetype: "Memory", core: "Ancestral code." },
  "46": { name: "K.Maraş", archetype: "Direnç", core: "Ayakta kal." },
  "47": { name: "Mardin", archetype: "Code", core: "Symbol layer." },
  "48": { name: "Muğla", archetype: "Rüzgar", core: "Free flow." },
  "49": { name: "Mus", archetype: "Stagnation", core: "Standby frequency." },
  "50": { name: "Nevşehir", archetype: "Underground", core: "Hidden area." },
  "51": { name: "Niğde", archetype: "Center", core: "Internal balance." },
  "52": { name: "Ordu", archetype: "Tepe", core: "Yüksek bakış." },
  "53": { name: "Rize", archetype: "Rain", core: "Cleanup." },
  "54": { name: "Sakarya", archetype: "Flow", core: "Continuous motion." },
  "55": { name: "Samsun", archetype: "Launcher", core: "First step." },
  "56": { name: "Siirt", archetype: "Inner world", core: "Deep meditation." },
  "57": {
    name: "Sinop",
    archetype: "Endpoint",
    core: "Boundary consciousness.",
  },
  "58": { name: "Sivas", archetype: "Boşluk", core: "Yalınlık." },
  "59": { name: "Tekirdağ", archetype: "Passage", core: "Thrace gate." },
  "60": { name: "Slap", archetype: "Hardness", core: "Clear decision." },
  "61": { name: "Trabzon", archetype: "Dalga", core: "Hareketli zihin." },
  "62": {
    name: "Tunceli",
    archetype: "Free spirit",
    core: "Unregulated consciousness.",
  },
  "63": { name: "Şanlıurfa", archetype: "Prophetic", core: "Ancient message." },
  "64": { name: "Butler", archetype: "First step", core: "New consciousness." },
  "65": { name: "Van", archetype: "Lake", core: "Deep reflection." },
  "66": { name: "Yozgat", archetype: "Patience", core: "Slow construction." },
  "67": { name: "Zonguldak", archetype: "Kömür", core: "Yeraltı enerji." },
  "68": { name: "Aksaray", archetype: "Kapı", core: "Gate frequency." },
  "69": { name: "Bayburt", archetype: "Loneliness", core: "Inner voice." },
  "70": { name: "Karaman", archetype: "Dil", core: "İfade gücü." },
  "71": { name: "Kırıkkale", archetype: "Metal", core: "Sert yapı." },
  "72": { name: "Batman", archetype: "Shadow", core: "Opposing energy." },
  "73": {
    name: "Şırnak",
    archetype: "Border line",
    core: "Extreme consciousness.",
  },
  "74": { name: "Bartın", archetype: "River", core: "Flow control." },
  "75": { name: "Ardahan", archetype: "Cold area", core: "Frozen memory." },
  "76": { name: "Iğdır", archetype: "Ova", core: "Open space." },
  "77": { name: "Yalova", archetype: "Rest", core: "Healing area." },
  "78": { name: "Karabük", archetype: "Steel", core: "Durability." },
  "79": {
    name: "Kilis",
    archetype: "Border crossing",
    core: "Identity query.",
  },
  "80": { name: "Osmaniye", archetype: "Protection", core: "Trust space." },
  "81": { name: "Düzce", archetype: "Reset", core: "Reset frequency." },
};
